### PR TITLE
add a startup.sh file

### PR DESCRIPTION
**Pull request by TarunDaCoder**
Sup bryant,
I added max's startup script with a few lil modifications :D
Like testing norg files and calculating the fastest config.

### CODE REVIEW

**Comment by TarunDaCoder** [comment]
never mind

**Comment by bryant-the-coder** [comment]
lemme see see (•‿•)(•‿•)

**Comment by bryant-the-coder** [comment]
closing as this is linux stuff ಠ_ಠ

**Comment by bryant-the-coder** [comment]
> never mind

dun be sad...

**Comment by TarunDaCoder** [comment]
> dun be sad...

lul im not sad

**Pull request closed without merging**
